theme: jekyll-theme-minimal
author:
  name: Maho Takahashi
  email: mtakahas@ucsd.edu
title: Maho Takahashi
description: Linguistics PhD Student at UC San Diego
# Analytics
analytics:
  provider               : "google-gtag"
  google:
    measurement_id          : "G-K90YMB1J1H"
